# Generated by Django 3.1.4 on 2020-12-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
            ],
        ),
    ]
