# Generated by Django 3.1.4 on 2020-12-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeloggerApp', '0002_auto_20201212_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='timestamp',
            field=models.DateField(verbose_name='date'),
        ),
    ]
