# Generated by Django 3.1.4 on 2020-12-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeloggerApp', '0003_auto_20201213_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_number', models.IntegerField(verbose_name='emp_number')),
                ('timeStamp', models.DateTimeField(verbose_name='datetime')),
            ],
        ),
    ]
