# Generated by Django 3.1.4 on 2020-12-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeloggerApp', '0004_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_number',
            field=models.IntegerField(default=555, verbose_name='emp_number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelog',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelog',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
